# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-11-01 08:33
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CorpMenu',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('menu', models.TextField(help_text='The current custom menu includes up to three first-level menus, each containing up to five second-level menus. A menu of up to four characters, two menus up to seven Chinese characters, more out of the part will be "..." instead. Please note that, after creating the custom menu, because the micro-client cache, you need 24-hour WeChat client will show up. Suggested that the test can try to cancel attention after the attention of the enterprise number, you can see the effect after the creation.', verbose_name='Menu')),
            ],
            options={
                'db_table': 'wechat_corp_menu',
                'verbose_name': 'CorpMenu',
                'verbose_name_plural': 'CorpMenus',
            },
        ),
        migrations.CreateModel(
            name='MPMenu',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('menu', models.TextField(help_text='The current custom menu includes up to three first-level menus, each containing up to five second-level menus. A menu of up to four characters, two menus up to seven Chinese characters, more out of the part will be "..." instead. Please note that, after creating the custom menu, because the micro-client cache, you need 24-hour WeChat client will show up. Suggested that the test can try to cancel attention after the attention of the enterprise number, you can see the effect after the creation.', verbose_name='Menu')),
            ],
            options={
                'db_table': 'wechat_mp_menu',
                'verbose_name': 'MPMenu',
                'verbose_name_plural': 'MpMenus',
            },
        ),
        migrations.CreateModel(
            name='WeixinCorp',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('token', models.CharField(max_length=50, verbose_name='Token')),
                ('aes_key', models.CharField(max_length=50, verbose_name='AESEncodingKey')),
                ('access_token', models.CharField(blank=True, max_length=512, null=True, verbose_name='AccessToken')),
                ('expire_time', models.DateTimeField(blank=True, null=True, verbose_name='Expire Time')),
                ('corpid', models.CharField(max_length=50, verbose_name='CorpID')),
                ('name', models.CharField(max_length=50, verbose_name='CorpName')),
                ('secret', models.CharField(max_length=50, verbose_name='CorpSecret')),
                ('agentid', models.SmallIntegerField(verbose_name='AgentID')),
                ('agent_name', models.CharField(max_length=50, verbose_name='AgentName')),
            ],
            options={
                'db_table': 'wechat_corp_server',
                'verbose_name': 'WechatCorp',
                'verbose_name_plural': 'WechatCorps',
            },
        ),
        migrations.CreateModel(
            name='WeixinMP',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='AppName')),
                ('secret', models.CharField(max_length=50, verbose_name='AppSecret')),
                ('token', models.CharField(max_length=50, verbose_name='Token')),
                ('aes_key', models.CharField(max_length=50, verbose_name='AESEncodingKey')),
                ('access_token', models.CharField(blank=True, max_length=512, null=True, verbose_name='AccessToken')),
                ('expire_time', models.DateTimeField(blank=True, null=True, verbose_name='Expire Time')),
                ('appid', models.CharField(max_length=50, unique=True, verbose_name='AppID')),
            ],
            options={
                'db_table': 'wechat_mp_server',
                'verbose_name': 'WechatMP',
                'verbose_name_plural': 'WechatMPs',
            },
        ),
        migrations.AlterUniqueTogether(
            name='weixincorp',
            unique_together=set([('corpid', 'secret', 'agentid')]),
        ),
        migrations.AddField(
            model_name='mpmenu',
            name='app',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='weixin.WeixinMP'),
        ),
        migrations.AddField(
            model_name='corpmenu',
            name='corp',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='weixin.WeixinCorp'),
        ),
    ]
