# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2017-02-02 10:19
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Banner',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, max_length=15, null=True, verbose_name='Title')),
                ('link', models.URLField(verbose_name='Link')),
                ('image', models.URLField(verbose_name='ImageURL')),
                ('description', models.TextField(blank=True, null=True, verbose_name='Description')),
                ('uuid', models.UUIDField(verbose_name='UUID')),
                ('order', models.SmallIntegerField(default=0, help_text='The order of the banner', verbose_name='Order')),
                ('title_size', models.SmallIntegerField(default='1.5', verbose_name='Title Size')),
                ('title_color', models.CharField(default='#ffffff', max_length=15, verbose_name='Title Color')),
            ],
            options={
                'db_table': 'portfolio_banner',
                'verbose_name': 'Banner',
                'verbose_name_plural': 'Banners',
            },
        ),
        migrations.CreateModel(
            name='Expection',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=15, verbose_name='Title')),
                ('description', models.TextField(verbose_name='Description')),
            ],
            options={
                'db_table': 'portfolio_expection',
                'verbose_name': 'Expection',
                'verbose_name_plural': 'Expection',
            },
        ),
        migrations.CreateModel(
            name='Experience',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start', models.DateField(verbose_name='Start')),
                ('end', models.DateField(verbose_name='End')),
                ('title', models.CharField(max_length=15, verbose_name='Title')),
                ('description', models.TextField(verbose_name='Description')),
            ],
            options={
                'db_table': 'portfolio_milestone',
                'verbose_name': 'Experience',
                'verbose_name_plural': 'Experience',
            },
        ),
        migrations.CreateModel(
            name='Skill',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=15, verbose_name='Name')),
                ('level', models.SmallIntegerField(verbose_name='Level(0-10)')),
                ('period', models.SmallIntegerField(verbose_name='Period(months)')),
                ('description', models.TextField(verbose_name='Description')),
            ],
            options={
                'db_table': 'portfolio_skill',
                'verbose_name': 'Skill',
                'verbose_name_plural': 'Skills',
            },
        ),
        migrations.CreateModel(
            name='SNS',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=15, verbose_name='Name')),
                ('sns_id', models.CharField(max_length=15, verbose_name='ID')),
                ('avatar', models.URLField(verbose_name='AvatarURL')),
                ('link', models.URLField(blank=True, help_text='The homepage of the platform', null=True, verbose_name='Link')),
                ('icon', models.URLField(help_text="The SNS paltform's icon url", verbose_name='IconURL')),
                ('platform', models.CharField(help_text="The SNS platform's name", max_length=15, verbose_name='Platform')),
            ],
            options={
                'db_table': 'portfolio_sns',
                'verbose_name': 'SNS',
                'verbose_name_plural': 'SNS',
            },
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=25, verbose_name='Name')),
                ('email', models.EmailField(blank=True, max_length=254, null=True, verbose_name='Email')),
                ('phone', models.CharField(blank=True, max_length=15, null=True, verbose_name='Phone')),
                ('nickname', models.CharField(max_length=25, verbose_name='Nick Name')),
                ('description', models.TextField(blank=True, null=True, verbose_name='Description')),
            ],
            options={
                'db_table': 'portfolio_user',
                'verbose_name': 'User',
                'verbose_name_plural': 'Users',
            },
        ),
        migrations.CreateModel(
            name='Works',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=15, verbose_name='Name')),
                ('url', models.URLField(help_text='The works page', verbose_name='URL')),
                ('description', models.TextField(verbose_name='Description')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='portfolio.User', verbose_name='User')),
            ],
            options={
                'db_table': 'portfolio_works',
                'verbose_name': 'Works',
                'verbose_name_plural': 'Works',
            },
        ),
        migrations.AddField(
            model_name='sns',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='portfolio.User', verbose_name='User'),
        ),
        migrations.AddField(
            model_name='skill',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='portfolio.User', verbose_name='User'),
        ),
        migrations.AddField(
            model_name='experience',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='portfolio.User', verbose_name='User'),
        ),
        migrations.AddField(
            model_name='expection',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='portfolio.User', verbose_name='User'),
        ),
    ]
