# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2017-02-02 10:32
from __future__ import unicode_literals

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='banner',
            name='title_size',
            field=models.FloatField(default=1.5, help_text='Title size use rem', verbose_name='Title Size'),
        ),
        migrations.AlterField(
            model_name='banner',
            name='uuid',
            field=models.UUIDField(default=uuid.uuid4, verbose_name='UUID'),
        ),
        migrations.AlterField(
            model_name='user',
            name='nickname',
            field=models.CharField(blank=True, max_length=25, null=True, verbose_name='Nick Name'),
        ),
    ]
