# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-02-04 09:29
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0003_auto_20170204_0935'),
    ]

    operations = [
        migrations.AlterField(
            model_name='banner',
            name='image',
            field=models.URLField(blank=True, null=True, verbose_name='ImageURL'),
        ),
    ]
