# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-04 15:06
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0006_auto_20170204_2229'),
    ]

    operations = [
        migrations.AlterField(
            model_name='banner',
            name='image',
            field=models.CharField(blank=True, help_text='The banner image url or data uri', max_length=200, null=True, verbose_name='Image'),
        ),
    ]
